using CsvHelper.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ContactsPhoneCsvTransform
{
    public sealed class PhoneContactGoogleMapToCsv : ClassMap<PhoneContactGoogle>
    {
        public PhoneContactGoogleMapToCsv()
        {
            Map(m => m.Name).Name("Name");
            Map(m => m.GivenName).Name("Given Name");
            Map(m => m.AdditionalName).Name("Additional Name");
            Map(m => m.FamilyName).Name("Family Name");
            Map(m => m.YomiName).Name("Yomi Name");
            Map(m => m.GivenNameYomi).Name("Given Name Yomi");
            Map(m => m.AdditionalNameYomi).Name("Additional Name Yomi");
            Map(m => m.FamilyNameYomi).Name("Family Name Yomi");
            Map(m => m.NamePrefix).Name("Name Prefix");
            Map(m => m.NameSuffix).Name("Name Suffix");
            Map(m => m.Initials).Name("Initials");
            Map(m => m.Nickname).Name("Nickname");
            Map(m => m.ShortName).Name("Short Name");
            Map(m => m.MaidenName).Name("Maiden Name");
            Map(m => m.Birthday).Name("Birthday");
            Map(m => m.Gender).Name("Gender");
            Map(m => m.Location).Name("Location");
            Map(m => m.BillingInformation).Name("Billing Information");
            Map(m => m.DirectoryServer).Name("Directory Server");
            Map(m => m.Mileage).Name("Mileage");
            Map(m => m.Occupation).Name("Occupation");
            Map(m => m.Hobby).Name("Hobby");
            Map(m => m.Sensitivity).Name("Sensitivity");
            Map(m => m.Priority).Name("Priority");
            Map(m => m.Subject).Name("Subject");
            Map(m => m.Notes).Name("Notes");
            Map(m => m.Language).Name("Language");
            Map(m => m.Photo).Name("Photo");
            Map(m => m.GroupMembership).Name("Group Membership");
            Map(m => m.E_mail1_Type).Name("E-mail 1 - Type");
            Map(m => m.E_mail1_Value).Name("E-mail 1 - Value");
            Map(m => m.E_mail2_Type).Name("E-mail 2 - Type");
            Map(m => m.E_mail2_Value).Name("E-mail 2 - Value");
            Map(m => m.E_mail3_Type).Name("E-mail 3 - Type");
            Map(m => m.E_mail3_Value).Name("E-mail 3 - Value");
            Map(m => m.IM1_Type).Name("IM 1 - Type");
            Map(m => m.IM1_Service).Name("IM 1 - Service");
            Map(m => m.IM1_Value).Name("IM 1 - Value");
            Map(m => m.Phone1_Type).Name("Phone 1 - Type");
            Map(m => m.Phone1_Value).Name("Phone 1 - Value");
            Map(m => m.Phone2_Type).Name("Phone 2 - Type");
            Map(m => m.Phone2_Value).Name("Phone 2 - Value");
            Map(m => m.Phone3_Type).Name("Phone 3 - Type");
            Map(m => m.Phone3_Value).Name("Phone 3 - Value");
            Map(m => m.Phone4_Type).Name("Phone 4 - Type");
            Map(m => m.Phone4_Value).Name("Phone 4 - Value");
            Map(m => m.Phone5_Type).Name("Phone 5 - Type");
            Map(m => m.Phone5_Value).Name("Phone 5 - Value");
            Map(m => m.Phone6_Type).Name("Phone 6 - Type");
            Map(m => m.Phone6_Value).Name("Phone 6 - Value");
            Map(m => m.Phone7_Type).Name("Phone 7 - Type");
            Map(m => m.Phone7_Value).Name("Phone 7 - Value");
            Map(m => m.Phone8_Type).Name("Phone 8 - Type");
            Map(m => m.Phone8_Value).Name("Phone 8 - Value");
            Map(m => m.Phone9_Type).Name("Phone 9 - Type");
            Map(m => m.Phone9_Value).Name("Phone 9 - Value");
            Map(m => m.Address1_Type).Name("Address 1 - Type");
            Map(m => m.Address1_Formatted).Name("Address 1 - Formatted");
            Map(m => m.Address1_Street).Name("Address 1 - Street");
            Map(m => m.Address1_City).Name("Address 1 - City");
            Map(m => m.Address1_POBox).Name("Address 1 - PO Box");
            Map(m => m.Address1_Region).Name("Address 1 - Region");
            Map(m => m.Address1_PostalCode).Name("Address 1 - Postal Code");
            Map(m => m.Address1_Country).Name("Address 1 - Country");
            Map(m => m.Address1_ExtendedAddress).Name("Address 1 - Extended Address");
            Map(m => m.Address2_Type).Name("Address 2 - Type");
            Map(m => m.Address2_Formatted).Name("Address 2 - Formatted");
            Map(m => m.Address2_Street).Name("Address 2 - Street");
            Map(m => m.Address2_City).Name("Address 2 - City");
            Map(m => m.Address2_POBox).Name("Address 2 - PO Box");
            Map(m => m.Address2_Region).Name("Address 2 - Region");
            Map(m => m.Address2_PostalCode).Name("Address 2 - Postal Code");
            Map(m => m.Address2_Country).Name("Address 2 - Country");
            Map(m => m.Address2_ExtendedAddress).Name("Address 2 - Extended Address");
            Map(m => m.Address3_Type).Name("Address 3 - Type");
            Map(m => m.Address3_Formatted).Name("Address 3 - Formatted");
            Map(m => m.Address3_Street).Name("Address 3 - Street");
            Map(m => m.Address3_City).Name("Address 3 - City");
            Map(m => m.Address3_POBox).Name("Address 3 - PO Box");
            Map(m => m.Address3_Region).Name("Address 3 - Region");
            Map(m => m.Address3_PostalCode).Name("Address 3 - Postal Code");
            Map(m => m.Address3_Country).Name("Address 3 - Country");
            Map(m => m.Address3_ExtendedAddress).Name("Address 3 - Extended Address");
            Map(m => m.Organization1_Type).Name("Organization 1 - Type");
            Map(m => m.Organization1_Name).Name("Organization 1 - Name");
            Map(m => m.Organization1_YomiName).Name("Organization 1 - Yomi Name");
            Map(m => m.Organization1_Title).Name("Organization 1 - Title");
            Map(m => m.Organization1_Department).Name("Organization 1 - Department");
            Map(m => m.Organization1_Symbol).Name("Organization 1 - Symbol");
            Map(m => m.Organization1_Location).Name("Organization 1 - Location");
            Map(m => m.Organization1_JobDescription).Name("Organization 1 - Job Description");
            Map(m => m.Relation1_Type).Name("Relation 1 - Type");
            Map(m => m.Relation1_Value).Name("Relation 1 - Value");
            Map(m => m.Relation2_Type).Name("Relation 2 - Type");
            Map(m => m.Relation2_Value).Name("Relation 2 - Value");
            Map(m => m.Relation3_Type).Name("Relation 3 - Type");
            Map(m => m.Relation3_Value).Name("Relation 3 - Value");
            Map(m => m.Relation4_Type).Name("Relation 4 - Type");
            Map(m => m.Relation4_Value).Name("Relation 4 - Value");
            Map(m => m.Relation5_Type).Name("Relation 5 - Type");
            Map(m => m.Relation5_Value).Name("Relation 5 - Value");
            Map(m => m.Relation6_Type).Name("Relation 6 - Type");
            Map(m => m.Relation6_Value).Name("Relation 6 - Value");
            Map(m => m.Relation7_Type).Name("Relation 7 - Type");
            Map(m => m.Relation7_Value).Name("Relation 7 - Value");
            Map(m => m.Relation8_Type).Name("Relation 8 - Type");
            Map(m => m.Relation8_Value).Name("Relation 8 - Value");
            Map(m => m.Relation9_Type).Name("Relation 9 - Type");
            Map(m => m.Relation9_Value).Name("Relation 9 - Value");
            Map(m => m.Relation10_Type).Name("Relation 10 - Type");
            Map(m => m.Relation10_Value).Name("Relation 10 - Value");
            Map(m => m.Relation11_Type).Name("Relation 11 - Type");
            Map(m => m.Relation11_Value).Name("Relation 11 - Value");
            Map(m => m.Relation12_Type).Name("Relation 12 - Type");
            Map(m => m.Relation12_Value).Name("Relation 12 - Value");
            Map(m => m.Relation13_Type).Name("Relation 13 - Type");
            Map(m => m.Relation13_Value).Name("Relation 13 - Value");
            Map(m => m.Relation14_Type).Name("Relation 14 - Type");
            Map(m => m.Relation14_Value).Name("Relation 14 - Value");
            Map(m => m.Website1_Type).Name("Website 1 - Type");
            Map(m => m.Website1_Value).Name("Website 1 - Value");
            Map(m => m.Website2_Type).Name(",Website 2 - Type");
            Map(m => m.Website2_Value).Name("Website 2 - Value");
            Map(m => m.Website3_Type).Name("Website 3 - Type");
            Map(m => m.Website3_Value).Name("Website 3 - Value");
            Map(m => m.Website4_Type).Name("Website 4 - Type");
            Map(m => m.Website4_Value).Name("Website 4 - Value");
            Map(m => m.Event1_Type).Name("Event 1 - Type");
            Map(m => m.Event1_Value).Name("Event 1 - Value");
            Map(m => m.Event2_Type).Name("Event 2 - Type");
            Map(m => m.Event2_Value).Name("Event 2 - Value");
            Map(m => m.Event3_Type).Name("Event 3 - Type");
            Map(m => m.Event3_Value).Name("Event 3 - Value");
            Map(m => m.CustomField1_Type).Name("Custom Field 1 - Type");
            Map(m => m.CustomField1_Value).Name("Custom Field 1 - Value");
            Map(m => m.CustomField2_Type).Name("Custom Field 2 - Type");
            Map(m => m.CustomField2_Value).Name("Custom Field 2 - Value");

        }
    }
}
